-- Выполнить один раз в Supabase: SQL Editor → New query → Run.

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  district text not null default 'Центр',
  address text not null,
  deal text not null default 'Продажа' check (deal in ('Продажа','Аренда')),
  type text not null check (type in ('Квартира','Дом','Участок','Коммерция')),
  price integer not null check (price > 0),
  area numeric not null check (area > 0),
  rooms integer not null default 0 check (rooms >= 0),
  floor text not null default '—',
  image text not null default '',
  gallery jsonb not null default '[]'::jsonb,
  description text not null default '',
  features jsonb not null default '[]'::jsonb,
  badge text not null default 'Новинка',
  publication_status text not null default 'Черновик' check (publication_status in ('Черновик','Опубликован','Задаток','Продано')),
  condition text not null default 'Уточняется',
  house_material text not null default 'Уточняется',
  heating text not null default 'Уточняется',
  balcony text not null default 'Уточняется',
  bathroom text not null default 'Уточняется',
  furniture text not null default 'Уточняется',
  documents text not null default 'Уточняется',
  lot_area numeric not null default 0 check (lot_area >= 0),
  negotiable boolean not null default false,
  agent_id text not null default 'diana',
  active boolean not null default true,
  x double precision not null check (x between -180 and 180),
  y double precision not null check (y between -90 and 90),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  verified_at timestamptz not null default now()
);

create index if not exists properties_public_idx on public.properties(active, publication_status, id desc);

create table if not exists public.seller_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  city text not null,
  property_type text not null,
  note text not null default '',
  status text not null default 'Новая' check (status in ('Новая','В работе','Завершена')),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event text not null,
  path text not null default '/',
  property_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists analytics_event_created_idx on public.analytics_events(event, created_at desc);

create table if not exists public.submission_attempts (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  created_at timestamptz not null default now()
);
create index if not exists submission_fingerprint_created_idx on public.submission_attempts(fingerprint, created_at desc);

alter table public.properties enable row level security;
alter table public.seller_leads enable row level security;
alter table public.analytics_events enable row level security;
alter table public.submission_attempts enable row level security;

-- Доступ к таблицам идёт только через защищённые серверные маршруты Vercel.
-- Service Role обходит RLS; anon-пользователи не получают прямого доступа.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('property-images','property-images',true,6291456,array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set public=true,file_size_limit=6291456,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/avif'];

-- Стартовые объекты становятся обычными записями и доступны для редактирования в админке.
insert into public.properties (id,title,location,district,address,deal,type,price,area,rooms,floor,image,gallery,description,features,badge,publication_status,condition,house_material,heating,balcony,bathroom,furniture,documents,lot_area,negotiable,agent_id,x,y,active)
values
(1,'2-комнатная квартира на Котовского в Днестровске','Днестровск','Центр','ул. Котовского, 17','Продажа','Квартира',11500,56,2,'1 этаж','/demo-property-1.webp','["/demo-property-1.webp","/demo-property-2.webp","/demo-property-3.webp"]','Уютная двухкомнатная квартира на первом этаже. Хороший вариант для ремонта под себя.','["Общая площадь 56 м²","Жилая площадь 30 м²","Кухня 9 м²","Первый этаж"]','Выгодная цена','Опубликован','Под ремонт','Уточняется','Центральное','Уточняется','Уточняется','Уточняется','Уточняется',0,true,'oksana',29.913,46.617,true),
(2,'2-комнатная квартира на Котовского в Слободзее','Слободзея','Центр','ул. Котовского','Продажа','Квартира',19000,50,2,'5 / 5','/demo-property-2.webp','["/demo-property-2.webp","/demo-property-3.webp","/demo-property-1.webp"]','Квартира в середине дома с раздельными комнатами.','["Общая площадь 50 м²","Комнаты раздельные","Середина дома","Пятый этаж"]','Новый объект','Опубликован','Требует обновления','Уточняется','Центральное','Уточняется','Раздельный','Уточняется','Уточняется',0,true,'oksana',29.704,46.728,true),
(3,'Просторная 1-комнатная квартира у «Шерифа»','Тирасполь','Центр','ул. Карла Либкнехта / Мечникова','Продажа','Квартира',23000,50,1,'1 / 9','/demo-property-3.webp','["/demo-property-3.webp","/demo-property-1.webp","/demo-property-2.webp"]','Просторная однокомнатная квартира в котельцовом доме.','["Общая площадь 50 м²","Котельцовый дом","Мебель и техника остаются","Первый этаж из девяти"]','С мебелью','Опубликован','Жилое','Котельцовый','Уточняется','Уточняется','Уточняется','Остаётся','Уточняется',0,true,'yana',29.626,46.839,true),
(4,'3-комнатная квартира с переходной лоджией','Тирасполь','Красные Казармы','район Красных Казарм','Продажа','Квартира',68500,74,3,'4 / 9','/demo-property-4.webp','["/demo-property-4.webp","/demo-property-1.webp","/demo-property-2.webp","/demo-property-3.webp"]','Просторная трёхкомнатная квартира с удобной планировкой.','["Три комнаты","Переходная лоджия","Тирасполь","Консультация по документам"]','С лоджией','Опубликован','Хорошее','Уточняется','Уточняется','Переходная лоджия','Уточняется','Уточняется','Уточняется',0,true,'alena',29.631,46.842,true),
(5,'Дом в центре с участком 4 сотки','Тирасполь','Центр','пер. Свердлова','Продажа','Дом',92000,138,5,'1 этаж','/demo-property-5.webp','["/demo-property-5.webp","/demo-property-6.webp","/demo-property-7.webp"]','Дом в центре Тирасполя общей площадью 138 м² с участком 4 сотки.','["Площадь дома 138 м²","Участок 4 сотки","Центр Тирасполя","Пер. Свердлова"]','Дом с участком','Опубликован','Хорошее','Уточняется','Уточняется','Нет','Уточняется','Уточняется','Уточняется',4,true,'natalia',29.648,46.835,true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.properties','id'),greatest(coalesce((select max(id) from public.properties),1),1),true);
