export type Deal = "Продажа" | "Аренда";
export type Property = { id:number; title:string; location:string; district:string; address:string; deal:Deal; type:string; price:number; area:number; rooms:number; floor:string; badge?:string; lat:number; lng:number; image:string; gallery?:string[]; description?:string; features?:string[]; publicationStatus?:string; condition?:string; houseMaterial?:string; heating?:string; balcony?:string; bathroom?:string; furniture?:string; documents?:string; lotArea?:number; negotiable?:boolean; agentId?:string; verifiedAt?:string; updated:string };
export type StoredProperty = { id:number; title:string; location:string; district:string; address:string; deal:Deal; type:string; price:number; area:number; rooms:number; floor:string; badge?:string; x:number; y:number; image:string; gallery?:string; description?:string; features?:string; publicationStatus?:string; condition?:string; houseMaterial?:string; heating?:string; balcony?:string; bathroom?:string; furniture?:string; documents?:string; lotArea?:number; negotiable?:boolean; agentId?:string; verifiedAt?:string; updatedAt?:string; createdAt?:string };

export const parseList=(value?:string)=>{try{const parsed=JSON.parse(value??"[]");return Array.isArray(parsed)?parsed.filter(item=>typeof item==="string"):[]}catch{return [] as string[]}};

const interiors=[
  "/demo-property-1.webp",
  "/demo-property-2.webp",
  "/demo-property-3.webp",
];

export const demo:Property[]=[
  {id:1,title:"2-комнатная квартира на Котовского",location:"Днестровск",district:"Центр",address:"ул. Котовского, 17",deal:"Продажа",type:"Квартира",price:11500,area:56,rooms:2,floor:"1 этаж",badge:"Выгодная цена",lat:46.617,lng:29.913,image:interiors[0],gallery:interiors,description:"Уютная двухкомнатная квартира на первом этаже. Хороший вариант для тех, кто хочет сделать ремонт под себя.",features:["Общая площадь 56 м²","Жилая площадь 30 м²","Кухня 9 м²","Первый этаж"],condition:"Под ремонт",houseMaterial:"Уточняется",heating:"Центральное",balcony:"Уточняется",bathroom:"Уточняется",furniture:"Уточняется",documents:"Уточняется",negotiable:true,verifiedAt:"2026-08-09",updated:"Проверено 9 августа 2026"},
  {id:2,title:"2-комнатная квартира на Котовского",location:"Слободзея",district:"Центр",address:"ул. Котовского",deal:"Продажа",type:"Квартира",price:19000,area:50,rooms:2,floor:"5 / 5",badge:"Новый объект",lat:46.728,lng:29.704,image:interiors[1],gallery:[interiors[1],interiors[2],interiors[0]],description:"Квартира в середине дома с раздельными комнатами. Подходит для жизни или как спокойный вариант под обновление.",features:["Общая площадь 50 м²","Комнаты раздельные","Середина дома","Пятый этаж"],condition:"Требует обновления",houseMaterial:"Уточняется",heating:"Центральное",balcony:"Уточняется",bathroom:"Раздельный",furniture:"Уточняется",documents:"Уточняется",negotiable:true,verifiedAt:"2026-08-09",updated:"Проверено 9 августа 2026"},
  {id:3,title:"Просторная 1-комнатная квартира у «Шерифа»",location:"Тирасполь",district:"Центр",address:"ул. Карла Либкнехта / Мечникова",deal:"Продажа",type:"Квартира",price:23000,area:50,rooms:1,floor:"1 / 9",badge:"С мебелью",lat:46.839,lng:29.626,image:interiors[2],gallery:[interiors[2],interiors[0],interiors[1]],description:"Просторная однокомнатная квартира в котельцовом доме. Мебель и техника остаются — можно планировать переезд без лишних расходов.",features:["Общая площадь 50 м²","Котельцовый дом","Мебель и техника остаются","Первый этаж из девяти"],condition:"Жилое",houseMaterial:"Котельцовый",heating:"Уточняется",balcony:"Уточняется",bathroom:"Уточняется",furniture:"Остаётся",documents:"Уточняется",negotiable:true,verifiedAt:"2026-08-09",updated:"Проверено 9 августа 2026"},
  {id:4,title:"3-комнатная квартира с переходной лоджией",location:"Тирасполь",district:"Красные Казармы",address:"район Красных Казарм",deal:"Продажа",type:"Квартира",price:68500,area:74,rooms:3,floor:"4 / 9",badge:"С лоджией",lat:46.842,lng:29.631,image:"/demo-property-4.webp",gallery:["/demo-property-4.webp",...interiors],description:"Просторная трёхкомнатная квартира с удобной планировкой и переходной лоджией. Подробности о комплектации и документах уточняйте у агента.",features:["Три комнаты","Переходная лоджия","Тирасполь","Консультация по документам"],condition:"Хорошее",houseMaterial:"Уточняется",heating:"Уточняется",balcony:"Переходная лоджия",bathroom:"Уточняется",furniture:"Уточняется",documents:"Уточняется",negotiable:true,verifiedAt:"2026-08-09",updated:"Проверено 9 августа 2026"},
  {id:5,title:"Дом в центре с участком 4 сотки",location:"Тирасполь",district:"Центр",address:"пер. Свердлова",deal:"Продажа",type:"Дом",price:92000,area:138,rooms:5,floor:"1 этаж",badge:"Дом с участком",lat:46.835,lng:29.648,image:"/demo-property-5.webp",gallery:["/demo-property-5.webp","/demo-property-6.webp","/demo-property-7.webp"],description:"Дом в центре Тирасполя общей площадью 138 м² с участком 4 сотки. Удобный вариант для семьи, которая хочет жить рядом с городской инфраструктурой.",features:["Площадь дома 138 м²","Участок 4 сотки","Центр Тирасполя","Пер. Свердлова"],condition:"Хорошее",houseMaterial:"Уточняется",heating:"Уточняется",balcony:"Нет",bathroom:"Уточняется",furniture:"Уточняется",documents:"Уточняется",lotArea:4,negotiable:true,verifiedAt:"2026-08-09",updated:"Проверено 9 августа 2026"},
];

const demoAssignments=["oksana","oksana","yana","alena","natalia"];
demo.forEach((property,index)=>{property.agentId=demoAssignments[index]??"diana"});
demo[0].title="2-комнатная квартира на Котовского в Днестровске";
demo[1].title="2-комнатная квартира на Котовского в Слободзее";

export const money=(value:number,deal:Deal)=>new Intl.NumberFormat("ru-RU").format(value)+` $${deal==="Аренда"?" / мес.":""}`;
export const imageUrl=(src:string,width:number)=>src.includes("images.unsplash.com")?`${src}?auto=format&fit=crop&fm=webp&w=${width}&q=72`:src;
export const objectCount=(value:number)=>{const mod100=value%100,mod10=value%10;const word=mod100>=11&&mod100<=14?"объектов":mod10===1?"объект":mod10>=2&&mod10<=4?"объекта":"объектов";return `${value} ${word}`};
export const verifiedLabel=(value?:string)=>value?`Проверено ${new Date(value).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}`:"Актуальность уточняется";
